version: "3.8"

x-default-app:
  &default-app
  build:
    context: .
    dockerfile: ./docker/Dockerfile
    target: dev
  env_file:
    - ./docker/local.env
    - .env
  volumes:
    - .:/app
  stdin_open: true
  tty: true

services:
  fastapi:
    <<: *default-app
    ports:
      - 8000:8000

  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=frost-shard
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data: {}
